# Generated by Django 5.0.1 on 2024-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quatity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
