# Generated by Django 5.0.1 on 2024-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_quatity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quatity',
            field=models.IntegerField(default=1),
        ),
    ]
