# Generated by Django 5.0.1 on 2024-01-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_quatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
